#theme: jekyll-theme-cayman
#theme: jekyll-theme-midnight
#theme: jekyll-theme-slate
theme: jekyll-theme-minimal
title: Naoiyuuma Pages
descreption: 筑波大学M1. ビッグデータ分析やデータマイニングの高速化の研究をしています. 
logo: img/icon.JPG
